import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/Hero'
import Typography from '@mui/material/Typography'
import { Button,Box } from '@mui/material'
import Header from '@/components/Layouts/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BareRock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main>
<Header />
{/* <Box sx={{width:'100%',height:'100vh',backgroundColor:'black',overflow:'hidden'}}> */}
<Hero />
{/* </Box> */}
<Box sx={{width:'100%;',height:'100vh',backgroundColor:'#1c1d3a',zIndex:9999999}}>
some stuff
</Box>
<Box sx={{width:'100%;',height:'100vh',backgroundColor:'#fff'}}>
some stuff
</Box>
{/* <Typography variant="h1" component="h1" gutterBottom>Isn&apos;t it time</Typography> */}
    </main>
    </>
  )
}
