import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/Home/Hero'
import Typography from '@mui/material/Typography'
import { Button,Box, Stack } from '@mui/material'
import Header from '@/components/Layouts/Header'
import ContentBox from '@/components/Home/IntroSection/ContentBox'
import IntroSection from '@/components/Home/IntroSection'
import Footer from '@/components/Layouts/Footer'
import Wrapper from '@/components/Layouts/Wrapper'
import MessagingAnim from '@/components/Home/MessageAnim'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>BareRock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main>
      <Hero />
      <MessagingAnim />
      <IntroSection />


    </main>
    </Wrapper>
  )
}
